.Dd August 9, 2022
.Dt XRANCO 1
.Sh NAME
.Nm xranco
.Nd random color generator for X
.Sh SYNOPSIS
.Nm
.Op Fl hv123456789
.Op Fl l Ar palette_file
.Sh DESCRIPTION
The
.Nm
application lets you generate 1 to 9 random colors and regenerate a specific color using the 1-9 number keys.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl #
generate that specific number of colors
.It Fl l
load palette from file
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It preview a color
echo '#fe8f3a' | xranco -l /dev/stdin
.El
.Sh PALETTE FORMAT
.Bl -tag -width indent
.It sample palette file
#199fef
.br
#e2cb97
.br
#e9e2ab
.br
#fe8f3a
.br
#cff501
.El
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xranco/issues
