.Dd August 3, 2022
.Dt XRANCO 1
.Sh NAME
.Nm xranco
.Nd random color generator for X
.Sh SYNOPSIS
.Nm
.Op Fl hv123456789
.Sh DESCRIPTION
The
.Nm
application lets you generate random colors.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h, -help
show usage
.It Fl v, -version
display the program version
.It Fl 1, 2, 3, 4, 5, 6, 7, 8, 9
generate that specific number of colors
.El
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xranco/issues
