.Dd August 8, 2022
.Dt XRANCO 1
.Sh NAME
.Nm xranco
.Nd random color generator for X
.Sh SYNOPSIS
.Nm
.Op Fl hlv123456789
.Sh DESCRIPTION
The
.Nm
application lets you generate random colors using the 1-9 number keys.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl l
load palette from file
.It Fl v
display the program version
.It Fl 1, 2, 3, 4, 5, 6, 7, 8, 9
generate that specific number of colors
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It preview a color
echo '#fe8f3a' | xranco -l /dev/stdin
.El
.Sh PALETTE FORMAT
.Bl -tag -width indent
.It sample palette file
#199fef
.br
#e2cb97
.br
#e9e2ab
.br
#fe8f3a
.br
#cff501
.El
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xranco/issues
